name = "website-builder-saas"
main = "./build/server/index.js" # For `wrangler pages dev`
pages_build_output_dir = "./build/client"
compatibility_date = "2023-10-30"

[vars]
APP_URL = "https://websitebuilder-7qa.pages.dev/"
# For production, set SUPABASE_URL and SUPABASE_ANON_KEY as secrets in your Cloudflare dashboard

[[d1_databases]]
binding = "DB" # This should match the `env.DB` access in your code
database_name = "website-builder-saas-db"
database_id = "184be39e-72d4-4c80-854a-8f669dae11b0"
preview_database_id = "184be39e-72d4-4c80-854a-8f669dae11b0" # Often the same as above
